version: "3"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
